spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://ep-white-cloud-44145397.ap-southeast-1.aws.neon.tech/jw_test?sslmode=require
    username: tndduc
    password: hbMeo2rtA4jL

server:
  tomcat:
    accesslog:
      enabled: true
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: secretkey
    expirationMs: 6000000
    refreshExpirationMs: 1200000000
