spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_wise?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  jwt:
    secret: secretkey
    expirationMs: 6000000
    refreshExpirationMs: 1200000000